[workspace]

members = [
    "vfc",
    "sayre",
    "quadrantal",
    "minifb-frontend",
    "hunt",
]

[profile.dev]
opt-level = 1

# Set the default for dependencies.
[profile.dev.package."*"]
opt-level = 3

