[package]
name = "hunt"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vfc = { path = "../vfc" }
image = "0.24.5"
minifb = "*"
